import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Time Technology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title as string}</title>
        <meta name="description" content={metadata.description as string} />
      </head>
      <body suppressHydrationWarning={true}>
        {children}
      </body>
    </html>
  );
}